### ISSUE TITLE
[Bug]: URI references in table are not included in Document

### ISSUE THREAD

**Issue by DamianFlynn** [innofactororg/ghw-markdown-convert#11]
### Operating system

Action

### Terraform Version

N/A

### Bug description

URLs which are added within a table, are displayed with a short link - for example

![image](https://user-images.githubusercontent.com/6288143/192782352-9271c4f6-e8b6-4cfb-9e6a-7a6320e8ec36.png)

However, the links are not included at the end of each page for references

![image](https://user-images.githubusercontent.com/6288143/192782478-5b9d8fc9-a958-4bc7-8735-376a737ad998.png)

### Steps to reproduce

This can been observed in the Training program document build pipeline - https://github.com/innofactororg/acf-solution-virtual_datacenter/pull/1

**Comment by ghost** [comment]
This seems to be fixed now after latest updates:
![image](https://user-images.githubusercontent.com/5260092/201497583-d13185a5-b802-4157-8ee3-2d56a064b905.png)

Action for above image: <https://github.com/innofactororg/acf-solution-virtual_datacenter/actions/runs/3452777238>

The table is however not very presentable, perhaps in this case because it is unable to determine MS Learn Path column width from link description and instead use the whole url length. An alternative option is to use a bullet list:
![image](https://user-images.githubusercontent.com/5260092/201419643-546c5df2-a079-42ca-a004-935bc0467ac6.png)
